[package]
name = "jito-packet-blaster"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = { workspace = true }
clap = { workspace = true }
env_logger = { workspace = true }
futures-util = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
once_cell = { workspace = true }
quinn = { workspace = true }
rustls = { workspace = true }
solana-client = { workspace = true }
solana-sdk = { workspace = true }
solana-streamer = { workspace = true }
solana-connection-cache = { workspace = true }
solana-quic-client = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

pkcs8 = { version = "0.8.0", features = ["alloc"] }
rcgen = "0.9.3"
